version: '3.8'
services:
  gateway-service:
    build:
      context: ./base-service/gateway-service
      args:
        SERVER_PORT: 8080
        NACOS_HOST: 172.17.0.1
        SENTINEL_HOST: 172.17.0.1
        SERVICE_IP: gateway-service
        SEATA_HOST: 172.17.0.1
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      - NACOS_HOST=172.17.0.1
      - SENTINEL_HOST=172.17.0.1
      - SERVICE_IP=gateway-service
      - SEATA_HOST=172.17.0.1
    restart: always
  business-service:
    build:
      context: ./base-service/business-service
      args:
        SERVER_PORT: 8000
        DB_HOST: 172.17.0.1
        NACOS_HOST: 172.17.0.1
        SENTINEL_HOST: 172.17.0.1
        SEATA_HOST: 172.17.0.1
        SERVICE_IP: business-service
    container_name: business-service
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=172.17.0.1
      - NACOS_HOST=172.17.0.1
      - SENTINEL_HOST=172.17.0.1
      - SEATA_HOST=172.17.0.1
      - SERVICE_IP=business-service
    restart: always
  goods-service:
    build:
      context: ./base-service/goods-service
      args:
        SERVER_PORT: 8010
        DB_HOST: 172.17.0.1
        NACOS_HOST: 172.17.0.1
        SENTINEL_HOST: 172.17.0.1
        SEATA_HOST: 172.17.0.1
        SERVICE_IP: goods-service
    container_name: goods-service
    ports:
      - "8010:8010"
    environment:
      - DB_HOST=172.17.0.1
      - NACOS_HOST=172.17.0.1
      - SENTINEL_HOST=172.17.0.1
      - SEATA_HOST=172.17.0.1
      - SERVICE_IP=goods-service
    restart: always
  order-service:
    build:
      context: ./base-service/order-service
      args:
        SERVER_PORT: 8020
        DB_HOST: 172.17.0.1
        NACOS_HOST: 172.17.0.1
        SENTINEL_HOST: 172.17.0.1
        SEATA_HOST: 172.17.0.1
        SERVICE_IP: order-service
    container_name: order-service
    ports:
      - "8020:8020"
    environment:
      - DB_HOST=172.17.0.1
      - NACOS_HOST=172.17.0.1
      - SENTINEL_HOST=172.17.0.1
      - SEATA_HOST=172.17.0.1
      - SERVICE_IP=order-service
    restart: always
  user-service:
    build:
      context: ./base-service/user-service
      args:
        SERVER_PORT: 8030
        DB_HOST: 172.17.0.1
        NACOS_HOST: 172.17.0.1
        SENTINEL_HOST: 172.17.0.1
        SEATA_HOST: 172.17.0.1
        SERVICE_IP: user-service
    container_name: user-service
    ports:
      - "8030:8030"
    environment:
      - DB_HOST=172.17.0.1
      - NACOS_HOST=172.17.0.1
      - SENTINEL_HOST=172.17.0.1
      - SEATA_HOST=172.17.0.1
      - SERVICE_IP=user-service
    restart: always

