server:
  port: 8080

spring:
  config:
    import: optional:nacos:application.yml
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        ip: 127.0.0.1
        server-addr: 127.0.0.1:8848
        namespace: public
        group: DEFAULT_GROUP
      config:
        server-addr: 127.0.0.1:8848
        namespace: public
        group: DEFAULT_GROUP
        file-extension: yml
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # 基础接口路由
        - id: web-service
          uri: lb://user-service
          predicates:
            - Path=/login,/register,/updatePassword
          filters:
            - StripPrefix=0

        # 用户服务路由
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=0
            
        # 商品服务路由
        - id: goods-service
          uri: lb://goods-service
          predicates:
            - Path=/goods/**
          filters:
            - StripPrefix=0
            
        # 分类服务路由
        - id: category-service
          uri: lb://goods-service
          predicates:
            - Path=/category/**
          filters:
            - StripPrefix=0
            
        # 订单服务路由
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=0
            
        # 购物车服务路由
        - id: cart-service
          uri: lb://order-service
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=0
            
        # 商家服务路由
        - id: business-service
          uri: lb://business-service
          predicates:
            - Path=/business/**
          filters:
            - StripPrefix=0
            
        # 地址服务路由
        - id: address-service
          uri: lb://user-service
          predicates:
            - Path=/address/**
          filters:
            - StripPrefix=0
            
        # 文件上传服务路由
        - id: files-service
          uri: lb://user-service
          predicates:
            - Path=/files/**
          filters:
            - StripPrefix=0
            
        # 通知服务路由
        - id: notice-service
          uri: lb://user-service
          predicates:
            - Path=/notice/**
          filters:
            - StripPrefix=0
            
        # 管理员服务路由
        - id: admin-service
          uri: lb://user-service
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=0
            

#网关服务已经集成了Sentinel进行流量控制
#限流规则从Nacos配置中心动态获取
#当触发限流时，会返回429状态码和指定的错误信息
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
        port: 8718
      datasource:
        ds:
          nacos:  # 从Nacos加载限流规则
            server-addr: 127.0.0.1:8848
            dataId: gateway-sentinel-rules
            groupId: DEFAULT_GROUP
            rule-type: gw-flow    # 网关流控规则类型
      scg:
        fallback:   # 限流降级配置
          mode: response
          response-status: 429
          response-body: {"code":"429","msg":"服务繁忙，请稍后重试"}

# 日志配置
logging:
  level:
    org.springframework.cloud.gateway: debug
    com.example.gateway: debug 

management:
  endpoints:
    web:
      exposure:
        include: "*" 